name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.*'  

    - name: Publish .NET application
      run: dotnet publish -o "./out"

    - name: Verify publish
      run: ls -la ./out

    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.REMOTE_PORT }}
        source: "./out/*"
        target: "$PATH/2"

    - name: Run commands on remote server
      uses: appleboy/ssh-action@v0.1.0
      with:
        port: 3000
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.PASSWORD }}
        script: |
            sudo systemctl start aspTest
